services:
  - type: web
    name: matraraksha-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0